@HostAddress = https://localhost:5003

### Presign URL
# @name presignUrl
POST {{HostAddress}}/api/v1/media/presign-url
Content-Type: application/json
Accept: application/json

{
  "fileName": "test-image.jpg",
  "contentType": "image/jpeg",
  "fileSize": 1048576,
  "entityType": "user-avatar",
  "entityId": "d3b07384-d9a4-4a5f-8c1c-3f2d2b5b3c4d"
}

### Upload File
@uploadUrl = {{presignUrl.response.body.uploadUrl}}

PUT {{uploadUrl}}
x-ms-blob-type: BlockBlob
Content-Type: image/svg

< ./shopee.png
### Confirm Upload
@fileId = {{presignUrl.response.body.fileId}}

POST {{HostAddress}}/api/v1/media/{{fileId}}/confirm
Content-Type: application/json
Accept: application/json

