properties:
  configuration:
    secrets:
      - name: db-connection
        value: ${{ secrets.CONNECTION_STRING_USER_SERVICE_DB }}
      - name: google-client-id
        value: ${{ secrets.GOOGLE_CLIENT_ID }}
      - name: google-client-secret
        value: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      - name: duende-license
        value: ${{ secrets.DUENDE_LICENSE_KEY }}
      - name: mediatr-license
        value: ${{ secrets.MEDIATR_LICENSE_KEY }}
      - name: smtp-user
        value: ${{ secrets.SMTP_USER }}
      - name: smtp-password
        value: ${{ secrets.SMTP_PASSWORD }}
  template:
    containers:
      - name: user-service
        env:
          # Application Configuration
          - name: ASPNETCORE_ENVIRONMENT
            value: 'Development'

          # Logging Configuration
          - name: Serilog__MinimumLevel__Default
            value: 'Debug'
          - name: Serilog__MinimumLevel__Override__Microsoft
            value: 'Information'
          - name: Serilog__MinimumLevel__Override__System
            value: 'Information'

          # Application URLs
          - name: DefaultRedirectUrl
            value: ${{ vars.DEFAULT_REDIRECT_URL }}
          - name: Issuer
            value: ${{ vars.ISSUER_URL }}

          # Database Configuration
          - name: ConnectionStrings__UserServiceDb
            secretRef: db-connection

          # Admin Portal Client Configuration
          - name: Clients__adminportal__ClientUri
            value: ${{ vars.ADMIN_PORTAL_CLIENT_URI }}
          - name: Clients__adminportal__RedirectUris__0
            value: ${{ vars.ADMIN_PORTAL_REDIRECT_URI }}
          - name: Clients__adminportal__PostLogoutRedirectUris__0
            value: ${{ vars.ADMIN_PORTAL_LOGOUT_REDIRECT_URI }}
          - name: Clients__adminportal__AllowedCorsOrigins__0
            value: ${{ vars.ADMIN_PORTAL_CORS_ORIGIN }}

          # Seller Center Client Configuration
          - name: Clients__sellercenter__ClientUri
            value: ${{ vars.SELLER_CENTER_CLIENT_URI }}
          - name: Clients__sellercenter__RedirectUris__0
            value: ${{ vars.SELLER_CENTER_REDIRECT_URI }}
          - name: Clients__sellercenter__PostLogoutRedirectUris__0
            value: ${{ vars.SELLER_CENTER_LOGOUT_REDIRECT_URI }}
          - name: Clients__sellercenter__AllowedCorsOrigins__0
            value: ${{ vars.SELLER_CENTER_CORS_ORIGIN }}

          # Web UI Client Configuration
          - name: Clients__webui__ClientUri
            value: ${{ vars.WEBUI_CLIENT_URI }}
          - name: Clients__webui__RedirectUris__0
            value: ${{ vars.WEBUI_REDIRECT_URI }}
          - name: Clients__webui__PostLogoutRedirectUris__0
            value: ${{ vars.WEBUI_LOGOUT_REDIRECT_URI }}
          - name: Clients__webui__AllowedCorsOrigins__0
            value: ${{ vars.WEBUI_CORS_ORIGIN }}

          # Authentication Configuration
          - name: Authentication__Google__ClientId
            secretRef: google-client-id
          - name: Authentication__Google__ClientSecret
            secretRef: google-client-secret

          # License Configuration
          - name: Duende__LicenseKey
            secretRef: duende-license
          - name: MediatR__LicenseKey
            secretRef: mediatr-license

          # Email Configuration
          - name: EmailSettings__SmtpServer
            value: ${{ vars.SMTP_SERVER }}
          - name: EmailSettings__SmtpPort
            value: ${{ vars.SMTP_PORT }}
          - name: EmailSettings__SmtpUser
            secretRef: smtp-user
          - name: EmailSettings__SmtpPassword
            secretRef: smtp-password
          - name: EmailSettings__FromEmail
            value: ${{ vars.FROM_EMAIL }}
          - name: EmailSettings__FromName
            value: ${{ vars.FROM_NAME }}
