name: Identity Service Workflow

on:
  push:
    branches: [ "master" ]
    paths: [ "src/HiveSpace.IdentityService/**", "test/HiveSpace.IdentityService/**" ]
  pull_request:
    types: [
      "opened",
      "synchronize",
      "reopened",
      "edited",
      ]
    branches: [ "master" ]
    paths: [ "src/HiveSpace.IdentityService/**", "test/HiveSpace.IdentityService/**" ]

jobs:
  build:
    name: Build IdentityService
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore src/HiveSpace.IdentityService/HiveSpace.IdentityService.Api/HiveSpace.IdentityService.Api.csproj

      - name: Build and Publish IdentityService
        run: dotnet publish src/HiveSpace.IdentityService/HiveSpace.IdentityService.Api/HiveSpace.IdentityService.Api.csproj --no-build --configuration Release -o ./publish-identity

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: identity-service-build
          path: ./publish-identity

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: identity-service-build
          path: ./publish-identity

      - name: Run Unit Tests
        run: dotnet test test/HiveSpace.IdentityService/HiveSpace.IdentityService.UnitTests/HiveSpace.IdentityService.UnitTests.csproj --no-build --configuration Release

      - name: Run Functional Tests
        run: dotnet test test/HiveSpace.IdentityService/HiveSpace.IdentityService.FunctionalTests/HiveSpace.IdentityService.FunctionalTests.csproj --no-build --configuration Release

  publish-artifact:
    name: Publish Artifact for Deployment
    runs-on: ubuntu-latest
    needs: [build, test]
    if: success()
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: identity-service-build
          path: ./publish-identity

      - name: Upload Final Deployment Artifact
        uses: actions/upload-artifact@v4
        with:
          name: identity-service-artifact
          path: ./publish-identity